theme: jekyll-theme-cayman
google_analytics: UA-38858139-15
repository: benkalsky/theColorName.scss
gems:
  - jekyll-github-metadata
  - jekyll-autoprefixer
title: theColorName
description: Mixin for all (141) CSS color names
show_downloads: true
sass:
    sass_dir: ./_scss
